workflows:
  build-interest-calculator:
    name: Build Interest calculator (Android)
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.example.interest_calculator"
    scripts:
      - name: Set Flutter SDK Versions
        script: |
          echo "flutter.compileSdkVersion=34" >> android/local.properties
          echo "flutter.targetSdkVersion=34" >> android/local.properties
          echo "flutter.minSdkVersion=21" >> android/local.properties
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
